trigger:
- main

pool:
  name: 'Azure'

steps:   # This 'steps' keyword was missing, which caused the parser to expect a key
- task: TerraformTaskV4@4
  inputs:
    provider: 'aws'
    command: 'init'
    backendServiceAWS: 'connection with AWS'
    backendAWSBucketName: 'k8statefile'
    backendAWSKey: 'terraform.tfstate'

- task: TerraformTaskV4@4
  inputs:
    provider: 'aws'
    command: 'validate'

- task: TerraformTaskV4@4
  inputs:
    provider: 'aws'
    command: 'plan'
    environmentServiceNameAWS: 'connection with AWS'

- task: TerraformTaskV4@4
  inputs:
    provider: 'aws'
    command: 'apply'
    environmentServiceNameAWS: 'connection with AWS'
